name: CI
on:
  pull_request:
  push:

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-2019
          - macos-10.15
        rust:
          - 1.55.0
          - nightly
    steps:
      - uses: actions/checkout@v2

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target/
          key: "cache-OS:${{ matrix.os }}-Rust:${{ matrix.rust }}-${{ hashFiles('./Cargo.toml') }}-${{ hashFiles('./Cargo.lock') }}"
          restore-keys: |
               "cache-OS:${{ matrix.os }}-Rust:${{ matrix.rust }}"

      - name: Build
        run: |
          cargo build

      - name: Test
        run: |
          cargo test